version: '3.8'
services:
  db:
    image: postgres:13
    user: root
    container_name: inver-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always             
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    networks:
      - invertropolis

  odoo14:
    image: odoo:14
    user: root
    container_name: inver-odoo14
    depends_on:
      - db
    ports:
      - "${PORT_ODOO}:8069"
    tty: true
    command: --
    environment:
      - HOST=${HOST_ODOO}
      - USER=${USER_ODOO}
      - PASSWORD=${PASSWORD_ODOO}
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
    networks:
      - invertropolis

  pgadmin:
    container_name: inver-pgadmin
    image: dpage/pgadmin4:4.14
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "${PORT_PGADMIN}:80"
    networks:
      - invertropolis
    restart: always

networks:
  invertropolis:
    driver: bridge

               